package com.wjs.member.model.level;

import java.io.Serializable;
import java.math.BigDecimal;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

public class CustLevel implements Serializable {
    /**
     * 标准ID -- cust_level.id
     * 创建时间 : 2017-04-13 15:30:44
     */
    private Long id;

    /**
     * 客户ID(网金所) -- cust_level.customer_id
     * 创建时间 : 2017-04-13 15:30:44
     */
    private String customerId;

    /**
     * 会员等级id -- cust_level.level_id
     * 创建时间 : 2017-04-13 15:30:44
     */
    private Long levelId;

    /**
     * 会员等级名称 -- cust_level.level_name
     * 创建时间 : 2017-04-13 15:30:44
     */
    private String levelName;

    /**
     * 修改时间戳 -- cust_level.modify_datetime
     * 创建时间 : 2017-04-13 15:30:44
     */
    private Long modifyDatetime;

    /**
     * 持有金额 -- cust_level.hold_amount
     * 创建时间 : 2017-04-13 15:30:44
     */
    private BigDecimal holdAmount;

    /**
     * 备注 -- cust_level.remark
     * 创建时间 : 2017-04-13 15:30:44
     */
    private String remark;

    /**
     * 历史最高持有本金 -- cust_level.max_hold_principle
     * 创建时间 : 2017-04-13 15:30:44
     */
    private BigDecimal maxHoldPrinciple;

    /**
     * 统计日期 -- cust_level.tx_date
     * 创建时间 : 2017-04-13 15:30:44
     */
    private Integer txDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_level.level_temp_id
     * 创建时间 : 2017-04-13 15:30:44
     */
    private Long levelTempId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_level.level_temp_name
     * 创建时间 : 2017-04-13 15:30:44
     */
    private String levelTempName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_level.level_temp_start_date
     * 创建时间 : 2017-04-13 15:30:44
     */
    private Integer levelTempStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_level.level_temp_end_date
     * 创建时间 : 2017-04-13 15:30:44
     */
    private Integer levelTempEndDate;

    /**
     * cust_level表的操作属性:serialVersionUID
     * 创建时间 : 2017-04-13 15:30:44
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 cust_level.id的get方法 
     * 创建时间 : 2017-04-13 15:30:44
     */
    public Long getId() {
        return id;
    }

    /**
     * 数据字段 cust_level.id的set方法
     * 创建时间 : 2017-04-13 15:30:44
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 数据字段 cust_level.customer_id的get方法 
     * 创建时间 : 2017-04-13 15:30:44
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * 数据字段 cust_level.customer_id的set方法
     * 创建时间 : 2017-04-13 15:30:44
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * 数据字段 cust_level.level_id的get方法 
     * 创建时间 : 2017-04-13 15:30:44
     */
    public Long getLevelId() {
        return levelId;
    }

    /**
     * 数据字段 cust_level.level_id的set方法
     * 创建时间 : 2017-04-13 15:30:44
     */
    public void setLevelId(Long levelId) {
        this.levelId = levelId;
    }

    /**
     * 数据字段 cust_level.level_name的get方法 
     * 创建时间 : 2017-04-13 15:30:44
     */
    public String getLevelName() {
        return levelName;
    }

    /**
     * 数据字段 cust_level.level_name的set方法
     * 创建时间 : 2017-04-13 15:30:44
     */
    public void setLevelName(String levelName) {
        this.levelName = levelName == null ? null : levelName.trim();
    }

    /**
     * 数据字段 cust_level.modify_datetime的get方法 
     * 创建时间 : 2017-04-13 15:30:44
     */
    public Long getModifyDatetime() {
        return modifyDatetime;
    }

    /**
     * 数据字段 cust_level.modify_datetime的set方法
     * 创建时间 : 2017-04-13 15:30:44
     */
    public void setModifyDatetime(Long modifyDatetime) {
        this.modifyDatetime = modifyDatetime;
    }

    /**
     * 数据字段 cust_level.hold_amount的get方法 
     * 创建时间 : 2017-04-13 15:30:44
     */
    public BigDecimal getHoldAmount() {
        return holdAmount;
    }

    /**
     * 数据字段 cust_level.hold_amount的set方法
     * 创建时间 : 2017-04-13 15:30:44
     */
    public void setHoldAmount(BigDecimal holdAmount) {
        this.holdAmount = holdAmount;
    }

    /**
     * 数据字段 cust_level.remark的get方法 
     * 创建时间 : 2017-04-13 15:30:44
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 数据字段 cust_level.remark的set方法
     * 创建时间 : 2017-04-13 15:30:44
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * 数据字段 cust_level.max_hold_principle的get方法 
     * 创建时间 : 2017-04-13 15:30:44
     */
    public BigDecimal getMaxHoldPrinciple() {
        return maxHoldPrinciple;
    }

    /**
     * 数据字段 cust_level.max_hold_principle的set方法
     * 创建时间 : 2017-04-13 15:30:44
     */
    public void setMaxHoldPrinciple(BigDecimal maxHoldPrinciple) {
        this.maxHoldPrinciple = maxHoldPrinciple;
    }

    /**
     * 数据字段 cust_level.tx_date的get方法 
     * 创建时间 : 2017-04-13 15:30:44
     */
    public Integer getTxDate() {
        return txDate;
    }

    /**
     * 数据字段 cust_level.tx_date的set方法
     * 创建时间 : 2017-04-13 15:30:44
     */
    public void setTxDate(Integer txDate) {
        this.txDate = txDate;
    }

    /**
     * 数据字段 cust_level.level_temp_id的get方法 
     * 创建时间 : 2017-04-13 15:30:44
     */
    public Long getLevelTempId() {
        return levelTempId;
    }

    /**
     * 数据字段 cust_level.level_temp_id的set方法
     * 创建时间 : 2017-04-13 15:30:44
     */
    public void setLevelTempId(Long levelTempId) {
        this.levelTempId = levelTempId;
    }

    /**
     * 数据字段 cust_level.level_temp_name的get方法 
     * 创建时间 : 2017-04-13 15:30:44
     */
    public String getLevelTempName() {
        return levelTempName;
    }

    /**
     * 数据字段 cust_level.level_temp_name的set方法
     * 创建时间 : 2017-04-13 15:30:44
     */
    public void setLevelTempName(String levelTempName) {
        this.levelTempName = levelTempName == null ? null : levelTempName.trim();
    }

    /**
     * 数据字段 cust_level.level_temp_start_date的get方法 
     * 创建时间 : 2017-04-13 15:30:44
     */
    public Integer getLevelTempStartDate() {
        return levelTempStartDate;
    }

    /**
     * 数据字段 cust_level.level_temp_start_date的set方法
     * 创建时间 : 2017-04-13 15:30:44
     */
    public void setLevelTempStartDate(Integer levelTempStartDate) {
        this.levelTempStartDate = levelTempStartDate;
    }

    /**
     * 数据字段 cust_level.level_temp_end_date的get方法 
     * 创建时间 : 2017-04-13 15:30:44
     */
    public Integer getLevelTempEndDate() {
        return levelTempEndDate;
    }

    /**
     * 数据字段 cust_level.level_temp_end_date的set方法
     * 创建时间 : 2017-04-13 15:30:44
     */
    public void setLevelTempEndDate(Integer levelTempEndDate) {
        this.levelTempEndDate = levelTempEndDate;
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}